import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  StatusBar,
  Image,
  Alert,
  Dimensions,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { generatePDFReport } from '../services/expo/fileHandler';
import { shareFile } from '../services/expo/sharing';
import { sendLocalNotification } from '../services/expo/notifications';
import { colors, radius, shadows, fonts } from '../theme';
import { useAssessment } from '../provider/AssessmentProvider';
import { scale } from '../utils/responsive';
import {
  FONT_SIZES,
  CONTAINER_PADDING,
  BOTTOM_NAV_HEIGHT,
  spacing,
  padding,
  gaps,
  borderRadius,
} from '../constants/layout';

const PROFILE_IMG = require('../assets/images/default_profile_photo.jpg');
const SHARE_ICON = require('../assets/icons/share-icon.png');

function CircularProgress({ percentage, label, value }) {
  const radius_val = 50;
  const circumference = 2 * Math.PI * radius_val;
  const filled = (percentage / 100) * circumference;

  return (
    <View style={cpStyles.container}>
      <View style={cpStyles.circleWrapper}>
        {/* Background ring */}
        <View style={cpStyles.ringBg} />
        {/* Value text */}
        <View style={cpStyles.valueContainer}>
          <Text style={cpStyles.value}>{value}</Text>
        </View>
      </View>
    </View>
  );
}

const cpStyles = StyleSheet.create({
  container: { alignItems: 'center' },
  circleWrapper: {
    width: 128,
    height: 128,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringBg: {
    position: 'absolute',
    width: 128,
    height: 128,
    borderRadius: 64,
    borderWidth: 10,
    borderColor: colors.primaryExtraLight,
  },
  valueContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  value: { fontSize: 24, fontWeight: '700', color: colors.white },
});

export default function ResultsDashboardScreen({ navigation, route }) {
  const assessment = useAssessment();

  // CRITICAL WORKFLOW GUARD: Prevent access without complete assessment
  React.useEffect(() => {
    // ❌ DO NOT ALLOW ACCESS IF:
    // 1. No OPG image uploaded
    // 2. Gender not selected
    // 3. All 7 teeth stages not selected
    // 4. No analysis results available

    if (!assessment.isOgpUploaded()) {
      Alert.alert(
        'Assessment Incomplete',
        'OPG image is required. Please start a new assessment.',
        [{ text: 'Start Assessment', onPress: () => navigation?.navigate('Home') }]
      );
      return;
    }

    if (!assessment.isGenderSelected()) {
      Alert.alert(
        'Gender Not Selected',
        'Patient gender must be selected before results can be displayed.',
        [{ text: 'Go Back', onPress: () => navigation?.goBack() }]
      );
      return;
    }

    if (!assessment.areAllStagesSelected()) {
      Alert.alert(
        'Stages Incomplete',
        'All 7 teeth must have Demirjian stages assigned.',
        [{ text: 'Go Back', onPress: () => navigation?.goBack() }]
      );
      return;
    }

    if (!assessment.state.maturityScore || !assessment.state.dentalAge) {
      Alert.alert(
        'No Analysis Data',
        'Assessment data is missing. Please complete the full workflow.',
        [{ text: 'New Assessment', onPress: () => navigation?.navigate('Home') }]
      );
      return;
    }
  }, []);

  // Use data from route params if available, otherwise fall back to assessment state
  const analysisData = route.params?.analysisData || {
    patient_id: assessment.state.patientId,
    maturity_score: assessment.state.maturityScore,
    dental_age: assessment.state.dentalAge,
    stages: assessment.state.toothStages,
  };

  const dentalAge = analysisData?.dental_age || assessment.state.dentalAge || 0;
  // Use a reasonable default chronological age or get from patient data if available
  const chronoAge = 12.4; // This would ideally come from patient profile data
  const delta = parseFloat((dentalAge - chronoAge).toFixed(1));

  const handleShare = async () => {
    try {
      const htmlContent = `
        <html>
          <body style="font-family: Arial; padding: 40px;">
            <h1>Dental Age Report</h1>
            <p><strong>Patient ID:</strong> ${analysisData?.patient_id || 'Anonymous'}</p>
            <p><strong>Chronological Age:</strong> ${chronoAge} years</p>
            <p><strong>Estimated Dental Age:</strong> ${dentalAge} years</p>
            <p><strong>Delta (Difference):</strong> ${delta > 0 ? '+' : ''}${delta} years</p>
            <p><strong>Maturity Score:</strong> ${analysisData?.maturity_score || 0}</p>
            <hr />
            <p><em>Generated by DentAge</em></p>
          </body>
        </html>
      `;
      // Use modular services
      const uri = await generatePDFReport(htmlContent);
      
      // Send notification about the report
      sendLocalNotification("Report Generated", "The dental age analysis PDF has been successfully created.");
      
      // Share it
      await shareFile(uri, 'Share Dental Age Report');
    } catch (error) {
      Alert.alert('Error', 'Failed to generate specific PDF report');
    }
  };

  return (
    <SafeAreaView style={styles.safe}>
      <StatusBar barStyle="dark-content" backgroundColor={colors.bgScreen} />

       {/* Top App Bar */}
       <View style={styles.topBar}>
         <View style={styles.topLeft}>
           <View style={styles.profileBorder}>
             <Image source={{ uri: PROFILE_IMG }} style={styles.profilePic} />
           </View>
           <View style={styles.profileInfo}>
             <Text style={styles.profileName}>{analysisData?.patient_id ? 'Patient ' + analysisData.patient_id : 'Anonymous'}</Text>
             <Text style={styles.profileSubtitle}>Dental Age Assessment</Text>
           </View>
         </View>
         <TouchableOpacity style={styles.shareBtn} onPress={handleShare}>
           <Image source={{ uri: SHARE_ICON }} style={styles.shareIcon} />
         </TouchableOpacity>
       </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* ── Bento Grid Hero ── */}

        {/* Maturity Score Card */}
        <View style={styles.maturityCard}>
          <Text style={styles.maturityLabel}>Skeletal Maturity Score</Text>
          <View style={styles.maturityCircle}>
            <CircularProgress 
              percentage={Math.min(Math.round((analysisData?.maturity_score || 0)), 100)} 
              value={String.fromCharCode(64 + Math.ceil((analysisData?.maturity_score || 0) / 12.5)) || 'E'}
            />
          </View>
          <Text style={styles.maturitySub}>Demirjian Stage · ${(analysisData?.maturity_score || 0) > 0 ? 'Calculated Maturity' : 'Awaiting Analysis'}</Text>
        </View>

        {/* Age Comparison Card */}
        <View style={styles.comparisonCard}>
          <View style={styles.comparisonTop}>
            <View style={styles.comparisonLeft}>
              <Text style={styles.comparisonTitle}>Age{'\n'}Analysis</Text>
              <Text style={styles.comparisonSub}>
                Benjamin{'\n'}Thorne
              </Text>
            </View>
            <View style={styles.deltaCard}>
              <Text style={styles.deltaIcon}>{delta > 0 ? '↑' : '↓'}</Text>
              <Text style={styles.deltaValue}>{delta > 0 ? '+' : ''}{delta}y</Text>
              <Text style={styles.deltaLabel}>Delta</Text>
            </View>
          </View>

          {/* Progress Bars */}
          <View style={styles.ageRows}>
            {/* Estimated Dental Age */}
            <View style={styles.ageRow}>
              <View style={styles.ageRowHeader}>
                <View style={styles.ageRowLeft}>
                  <Text style={styles.dotIndigo}>●</Text>
                  <Text style={styles.ageRowLabel}>Estimated Dental Age</Text>
                </View>
                <Text style={styles.ageRowValue}>{dentalAge} yrs</Text>
              </View>
              <View style={styles.progressBg}>
                <View style={[styles.progressFill, { width: '87%', backgroundColor: colors.indigo }]} />
              </View>
            </View>

            {/* Chronological Age */}
            <View style={styles.ageRow}>
              <View style={styles.ageRowHeader}>
                <View style={styles.ageRowLeft}>
                  <Text style={styles.dotGray}>●</Text>
                  <Text style={styles.ageRowLabel}>Chronological Age</Text>
                </View>
                <Text style={styles.ageRowValue}>{chronoAge} yrs</Text>
              </View>
              <View style={styles.progressBg}>
                <View style={[styles.progressFill, { width: '77%', backgroundColor: colors.textMuted }]} />
              </View>
            </View>
          </View>

          {/* Legend */}
          <View style={styles.legend}>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: colors.indigo }]} />
              <Text style={styles.legendLabel}>Dental Age</Text>
            </View>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: colors.textMuted }]} />
              <Text style={styles.legendLabel}>Chronological Age</Text>
            </View>
          </View>
        </View>

        {/* ── Secondary Insights ── */}
        <View style={styles.insightCard}>
          <View style={styles.insightHeader}>
            <Text style={styles.insightIcon}>🧠</Text>
            <Text style={styles.insightTitle}>Clinical Interpretation</Text>
          </View>
          <Text style={styles.insightBody}>
            The patient exhibits an advanced dental development relative to their 
            chronological age (+1.2 years). This acceleration is consistent with 
            normal physiological variation in early adolescence. No immediate 
            orthodontic intervention is suggested based on maturity alone.
          </Text>
        </View>

        {/* Dental Info Card */}
        <View style={styles.infoCard}>
          <View style={styles.insightHeader}>
            <Text style={styles.insightIcon}>🦷</Text>
            <Text style={styles.insightTitle}>Dental Information</Text>
          </View>
          <View style={styles.infoList}>
            {[
              { label: 'Assessment Tooth', value: 'Tooth 36', highlight: true },
              { label: 'Radiograph Type', value: 'OPG Panoramic' },
              { label: 'Classification Method', value: 'Demirjian' },
            ].map((item) => (
              <View key={item.label} style={styles.infoItem}>
                <Text style={styles.infoLabel}>{item.label}</Text>
                <View style={[styles.infoValueContainer, item.highlight && styles.infoValueHighlight]}>
                  <Text style={[styles.infoValue, item.highlight && styles.infoValueHighlightText]}>
                    {item.value}
                  </Text>
                </View>
              </View>
            ))}
          </View>
        </View>

        {/* ── Disclaimer ── */}
        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerIcon}>⚠</Text>
          <Text style={styles.disclaimerText}>
            This report is generated as a clinical support tool and should not 
            replace the professional judgment of a qualified dental practitioner. 
            Age estimation from dental development carries inherent biological 
            variation of ±1.2 years.
          </Text>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>

      {/* Bottom Nav */}
      <View style={styles.bottomNav}>
        {['Dashboard', 'Assessments', 'Settings'].map((tab, i) => (
          <TouchableOpacity
            key={tab}
            style={styles.navTab}
            onPress={() => {
              if (tab === 'Dashboard') navigation?.navigate('Home');
              if (tab === 'Settings') navigation?.navigate('Settings');
            }}
          >
            <Text style={[styles.navLabel, i === 1 && styles.navLabelActive]}>{tab.toUpperCase()}</Text>
          </TouchableOpacity>
        ))}
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bgScreen },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: CONTAINER_PADDING, paddingTop: spacing.lg, paddingBottom: spacing.xxl },

  // Top Bar
  topBar: {
    height: scale(64),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xxl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  topLeft: { flexDirection: 'row', alignItems: 'center', gap: gaps.md },
  profileBorder: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    borderWidth: 2,
    borderColor: colors.primaryLight,
    padding: spacing.xs,
    overflow: 'hidden',
  },
  profilePic: { width: '100%', height: '100%', borderRadius: scale(18) },
  topTitle: { fontSize: FONT_SIZES.xl, fontWeight: '700', color: colors.textPrimary, letterSpacing: -0.5 },
  shareBtn: { padding: spacing.sm, borderRadius: spacing.xl, backgroundColor: colors.bgCard, ...shadows.card },
  shareIcon: { width: gaps.lg, height: gaps.lg, resizeMode: 'contain' },

  // Maturity Score
  maturityCard: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.card,
    padding: padding.card,
    alignItems: 'center',
    marginBottom: gaps.lg,
    ...shadows.hero,
  },
  maturityLabel: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.8)',
    marginBottom: spacing.xxl,
  },
  maturityCircle: { marginBottom: gaps.lg },
  maturitySub: { fontSize: FONT_SIZES.sm, fontWeight: '400', color: 'rgba(255,255,255,0.7)', marginTop: spacing.xs },

  // Comparison Card
  comparisonCard: {
    backgroundColor: colors.bgCard,
    borderRadius: borderRadius.card,
    padding: padding.card,
    marginBottom: gaps.lg,
    ...shadows.card,
    gap: spacing.xxl,
  },
  comparisonTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  comparisonLeft: { gap: gaps.xs },
  comparisonTitle: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: '700',
    color: colors.textPrimary,
    letterSpacing: -0.5,
    lineHeight: scale(30),
  },
  comparisonSub: { fontSize: FONT_SIZES.lg, fontWeight: '400', color: colors.textSecondary, lineHeight: scale(20) },
  deltaCard: {
    backgroundColor: colors.primaryExtraLight,
    borderRadius: borderRadius.lg,
    padding: spacing.xl,
    alignItems: 'center',
    gap: spacing.xs,
    width: scale(100),
  },
  deltaIcon: { fontSize: FONT_SIZES.xs, color: colors.primary },
  deltaValue: { fontSize: scale(22), fontWeight: '700', color: colors.primary, letterSpacing: -0.5 },
  deltaLabel: { fontSize: FONT_SIZES.xs, fontWeight: '400', color: colors.textSecondary },

  ageRows: { gap: gaps.md },
  ageRow: { gap: gaps.xs },
  ageRowHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  ageRowLeft: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  dotIndigo: { fontSize: FONT_SIZES.xs, color: colors.indigo },
  dotGray: { fontSize: FONT_SIZES.xs, color: colors.textMuted },
  ageRowLabel: { fontSize: FONT_SIZES.sm, fontWeight: '500', color: colors.textSecondary },
  ageRowValue: { fontSize: FONT_SIZES.lg, fontWeight: '700', color: colors.textPrimary },
  progressBg: {
    height: spacing.xs,
    backgroundColor: colors.bgMuted,
    borderRadius: spacing.xs,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: spacing.xs },

  legend: { flexDirection: 'row', gap: spacing.xxl, paddingTop: spacing.xs, borderTopWidth: 1, borderTopColor: colors.border },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: gaps.xs },
  legendDot: { width: spacing.sm, height: spacing.sm, borderRadius: spacing.xs },
  legendLabel: { fontSize: FONT_SIZES.xs, color: colors.textSecondary },

  // Insight Card
  insightCard: {
    backgroundColor: colors.bgCard,
    borderRadius: borderRadius.card,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.xxl,
    marginBottom: gaps.lg,
    gap: gaps.md,
    ...shadows.card,
  },
  insightHeader: { flexDirection: 'row', alignItems: 'center', gap: gaps.xs },
  insightIcon: { fontSize: scale(18) },
  insightTitle: { fontSize: FONT_SIZES.lg, fontWeight: '600', color: colors.textPrimary },
  insightBody: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '400',
    color: colors.textSecondary,
    lineHeight: scale(20),
  },

  // Info Card
  infoCard: {
    backgroundColor: colors.bgCard,
    borderRadius: borderRadius.card,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.xxl,
    marginBottom: gaps.lg,
    gap: gaps.md,
    ...shadows.card,
  },
  infoList: { gap: gaps.md },
  infoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  infoLabel: { fontSize: FONT_SIZES.sm, fontWeight: '400', color: colors.textSecondary },
  infoValueContainer: {
    backgroundColor: colors.bgMuted,
    borderRadius: borderRadius.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  infoValueHighlight: { backgroundColor: colors.primaryExtraLight },
  infoValue: { fontSize: FONT_SIZES.sm, fontWeight: '600', color: colors.textPrimary },
  infoValueHighlightText: { color: colors.primary },

  // Disclaimer
  disclaimer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: gaps.md,
    backgroundColor: '#fffbeb',
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: '#fde68a',
    padding: spacing.xl,
    marginBottom: gaps.lg,
  },
  disclaimerIcon: { fontSize: scale(16), color: '#d97706' },
  disclaimerText: {
    flex: 1,
    fontSize: FONT_SIZES.xs,
    fontWeight: '400',
    color: '#92400e',
    lineHeight: scale(18),
  },

  // Bottom Nav
  bottomNav: {
    height: BOTTOM_NAV_HEIGHT,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  navTab: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navLabel: { fontSize: FONT_SIZES.xs, fontWeight: '500', color: colors.textMuted, letterSpacing: 0.3 },
  navLabelActive: { color: colors.primary, fontWeight: '700' },
});
